### ISSUE TITLE
query regarding contact topic names

### ISSUE THREAD

**Issue by rua0ra1** [lnotspotl/tbai#12]
Hi @lnotspotl ,

In the StatePublisher.ccp file you mentioned that hard coding of the contact names needs to be changed. 
```
// Setup contact flags - TODO(lnotspotl): This is a bit hacky, remove hardcoding!
    std::vector<std::string> contactTopics = {"/lf_foot_contact", "/rf_foot_contact", "/lh_foot_contact",
                                              "/rh_foot_contact"};
```

I am wondering why can't we define these contact names in the config file and read them here. What's your thoughts on that? And are there any other ways we can address this issue?. Thank you.

**Comment by lnotspotl** [comment]
Yeah, this makes total sense and thank you for bringing this up. This project should be robot-agnostic in the future, there shouldn't be any hardcoded values valid only for a single type of a robot.

Feel free to make the changes 💯

**Comment by rua0ra1** [comment]
Cheers mate. I will work on that over the weekend
