### ISSUE TITLE
humanoids robot support

### ISSUE THREAD

**Issue by ZhangLiang-Cencen** [lnotspotl/tbai#9]
Thanks for your good work!
Will this work support humanoids robot in the future?
Or 
Do you have any suggestions?
Thanks a lot!

**Comment by lnotspotl** [comment]
Hi,

yes, we are planning on adding support for humanoid robot controllers. Those will most likely be controllers trained in simulation, as that is where the field is heading right now. Take a look at the [IsaacLab](https://github.com/isaac-sim/IsaacLab) project, or more specifically their [examples](https://isaac-sim.github.io/IsaacLab/source/features/environments.html). They have there all the code needed to train a humanoid walking policy, so the goal would be to write a C++ wrapper around the underlying neural network producing the desired network inputs, post-processing the outputs and finally publishing the desired joint angles via ROS to the Gazebo simulator. Let me know if you have more questions and in case you are interested, you can start working on the initial support yourself. Contributions are always welcome.

**Comment by ZhangLiang-Cencen** [comment]
Thanks for your reply!
I will study your project and IsaacLab project.
And I hope to be able to contribute to this humanoid project in the future.

**Comment by lnotspotl** [comment]
Feel free to open a new issue if you have more questions.
